// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
//#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6be357ea-3f4b-4086-8c6c-98d093607a86";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTargetTemp1Change();
void onTargetTemp2Change();
void onAntiFreezeChange();

float room1Temp;
float room2Temp;
float targetTemp1;
float targetTemp2;
bool antiFreeze;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(room1Temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(room2Temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(targetTemp1, READWRITE, ON_CHANGE, onTargetTemp1Change);
  ArduinoCloud.addProperty(targetTemp2, READWRITE, ON_CHANGE, onTargetTemp2Change);
  ArduinoCloud.addProperty(antiFreeze, READWRITE, ON_CHANGE, onAntiFreezeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
